name: Docs

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'django_honeyguard/**'
      - 'pyproject.toml'
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install docs deps
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build docs
        working-directory: docs
        run: |
          make html

      - name: Upload built docs
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_build/html

